### ISSUE TITLE
Setting elasticities to zero?

### ISSUE THREAD

**Issue by hsauro** [exe0cdc/PyscesToolbox#1]
When symca is used to symbolically derive control equations, is it possible to set some elasticities (eg product elasticities) to zero before the symbolic calculation is carried out? This would be useful for generating simpler expressions.

**Comment by hsauro** [comment]
Rohwer, answered my question, use the following:

sc.cc_results.ccJR1_R3.expression.replace('ecR1_S1', '1')
sc.cc_results.ccJR1_R3.expression.replace('J_R1', '1')
sc.cc_results.ccJR1_R3.expression.replace('ecR2_S1', '0')

**Comment by exe0cdc** [comment]
A more efficient solution is to make the replacement before the inversion of the ematrix. Thus:

```Python
sc._ematrix = sc.ematrix.replace('ecR1_S1',0)
sc.do_symca()
```
Now all the control coefficients in `cc_results` will have simplification. This method also allows you to still have access to all the normal symca functionality (e.g. inspecting control patterns individually, having access to latex formatted text etc.).

As an aside, as of the latest release symca now has a simpler way of generating control coefficient expressions for models without a valid steady state. Details are on the release page at https://github.com/PySCeS/PyscesToolbox/releases/tag/0.8.6
